### ISSUE TITLE
Not available on NuGet

### ISSUE THREAD

**Issue by ChristopherSchubert** [FoundatioFx/Foundatio.Minio#1]
Is this package going to be published via NuGet?  I don't see a release tagged and can't find an available package.

**Comment by niemyjski** [comment]
Yes, we are waiting for the 7.x release of foundatio to push the packages which should happen soon. I was working to try and update the dependencies we ship with but am blocked currently. 

https://github.com/minio/minio-dotnet/pull/212

**Comment by niemyjski** [comment]
You can find this package currently on our nightly builds feed: https://www.myget.org/feed/Packages/exceptionless

**Comment by ChristopherSchubert** [comment]
Appreciate the help!
